name = "KV Redis"
language = "rust"
type = "provider"
version = "0.28.2"
wit = "../../../crates/provider-keyvalue-redis/wit"

[rust]
target_path = "../../../target"

[provider]
bin_name = "keyvalue-redis-provider"
vendor = "wasmCloud"
