name = "KV Nats"
language = "rust"
type = "provider"
version = "0.2.0"
wit = "../../../crates/provider-keyvalue-nats/wit"

[rust]
target_path = "../../../target"

[provider]
bin_name = "keyvalue-nats-provider"
vendor = "wasmCloud"
